import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Validate environment variables
if not os.getenv("GOOGLE_APPLICATION_CREDENTIALS") and not os.getenv("GOOGLE_WEB_CLIENT_SECRETS_FILE"):
    raise ValueError("GOOGLE_APPLICATION_CREDENTIALS environment variable not set")

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
os.environ["GOOGLE_WEB_CLIENT_SECRETS_FILE"] = os.getenv("GOOGLE_WEB_CLIENT_SECRETS_FILE")


GOOGLE_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_WEB_CLIENT_SECRETS_FILE = os.getenv("GOOGLE_WEB_CLIENT_SECRETS_FILE")
GOOGLE_WEB_CLIENT_ID = os.getenv("GOOGLE_WEB_CLIENT_ID")
GOOGLE_WEB_CLIENT_SECRET = os.getenv("GOOGLE_WEB_CLIENT_SECRET")
DATABASE_URL = os.getenv("DATABASE_URL")
EXTERNAL_DATABASE_URL = os.getenv("EXTERNAL_DATABASE_URL")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_USER_ID = os.getenv("TELEGRAM_USER_ID")
